# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Super Bundle Staging"
client_id = "693180954f2c0e9af09a587efe0e8830"
application_url = "https://ruled-justice-prescribed-climbing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ruled-justice-prescribed-climbing.trycloudflare.com/auth/callback",
  "https://ruled-justice-prescribed-climbing.trycloudflare.com/auth/shopify/callback",
  "https://ruled-justice-prescribed-climbing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[app_proxy]
url = "https://ruled-justice-prescribed-climbing.trycloudflare.com"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bundled-discount-app.myshopify.com"
