# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "super-bundle"
client_id = "8862891f33ff668f5c02a15365e80200"
application_url = "https://symbols-hardware-approximately-cork.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_publications,write_cart_transforms,read_orders"

[auth]
redirect_urls = [
  "https://symbols-hardware-approximately-cork.trycloudflare.com/auth/callback",
  "https://symbols-hardware-approximately-cork.trycloudflare.com/auth/shopify/callback",
  "https://symbols-hardware-approximately-cork.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "super-bundle.myshopify.com"
